python -u run.py \
  --task_name short_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ \
  --data_path bitcoin.csv \
  --model_id BTC_Test \
  --model TimeRecipe \
  --use_norm True \
  --use_decomp False \
  --emb_type patch \
  --ff_type mlp \
  --batch_size 32