python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ \
  --data_path nasdaq.csv \
  --model_id NASDAQ_Test \
  --model TimeRecipe \
  --use_norm False \
  --use_decomp True \
  --emb_type invert \
  --ff_type transformer \
  --batch_size 32